apiVersion: apps/v1
kind: Deployment
metadata:
  name: observatory-app
  namespace: observatory
  labels:
    app: observatory-app
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: observatory-app
  template:
    metadata:
      labels:
        app: observatory-app
      annotations:
        # Prometheus will scrape this pod automatically
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: app
          image: ghcr.io/sharanch/go-sre-observatory:latest
          imagePullPolicy: Always          # using ghcr image
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_VERSION
              value: "1.0.0"
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: observatory-app
  namespace: observatory
  labels:
    app: observatory-app
spec:
  selector:
    app: observatory-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
