apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: observatory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
        - name: loadgen
          image: ghcr.io/sharanch/loadgen:latest
          imagePullPolicy: Always
          env:
            - name: TARGET_URL
              value: "http://observatory-app"
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
